CapaPresentacion/Controllers/ArticulosController.cs
using CapaEntidad;
using CapaNegocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacion.Controllers
{
    public class ArticulosController : Controller
    {
        // GET: Articulos
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public JsonResult ObtenerArticulos()
        {
            List<Articulo> list = new List<Articulo>();
            list = new BLL_Articulo().ObtenerArticulos();

            return Json(new { data = list }, JsonRequestBehavior.AllowGet);
        }
    }
}

CapaPresentacion/Controllers/HomeController.cs
using CapaEntidad;
using CapaNegocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacion.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            Card card = new BLL_Card().ObtenerCards().FirstOrDefault();
            return View(card);
        }
    }
}

CapaPresentacion/Views/Articulos/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main>
    <div class="texto-principal">
        <h1 class="title valign-text-bottom">Articulos</h1>
    </div>
    <div class="container-table">
        <table id="tabla" class="tabla">
            <thead>
                <tr>
                    <th>Titulo</th>
                    <th>Descripción</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</main>

@section scripts{
    <script>
        $("#document").ready(function () {
            jQuery.ajax({
                url: '@Url.Action("ObtenerArticulos", "Articulos")',
                type: "GET",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    var articulos = data.data;
                    var tabla = $("#tabla tbody");
                    tabla.empty(); 

                    $.each(articulos, function (index, item) {
                        tabla.append(
                            '<tr>' +
                            '<td>' + item.Titulo + '</td>' + // Usamos Nombre como Titulo
                            '<td>' + item.Descripcion + '</td>' + // Descripción del artículo
                            '</tr>'
                        )
                    })
                }
            });
        })

    </script>
}

CapaPresentacion/Views/Home/Index.cshtml
@model CapaEntidad.Card
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main>
    <div class="texto-principal">
        <h1 class="title valign-text-bottom">@Model.TituloPrincipal</h1>
    </div>
    <div class="texto-secundario-tex-home">
        <p class="texto-secundario-tex-texto-secundario-tex">
            @Model.SubTitulo
        </p>
    </div>
    <div class="componente-informativo">
        <img class="caritas-negras" src="~/Recursos/img/caritas-negras@2x.png" alt="caritas negras" />
        <div class="flex-col">
            <div class="texto-sobre-otro-elemento-flex-col">
                <div class="texto-sobre-otro-elemento-texto-sobre-otro-elemento valign-text-middle">
                    @Model.TextoCardInformativo
                </div>
            </div>
            <div class="botn-7"><div class="botn-8 valign-text-middle">botón</div></div>
        </div>
    </div>
</main>

CapaPresentacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Prueba Tecnica Frontend</title>
    @Styles.Render("~/Content/css")
    
</head>
<body>
    <div class="container-center-horizontal">
        <div class="home screen">
            <header class="header">
                <div class="logo"></div>
                <div class="menu-responsive" id="menu" ">
                    <div class=" botn-2">
                        <div class="botn-3 valign-text-middle inter-medium-white-16px">
                            <a class="item-nav" href="@Url.Action("Index","Home")">Inicio</a>
                        </div>
                    </div>
                    <div class="botn-1">
                        <div class="botn-4 valign-text-middle inter-medium-white-16px">
                            <a class="item-nav" href="@Url.Action("Index","Articulos")">Articulos</a>
                        </div>
                    </div>
                    <div class="botn-1">
                        <div class="botn-5 valign-text-middle inter-medium-white-16px">botón</div>
                    </div>
                </div>
                <button id="menu-hamburguesa" class="menu-hamburguesa">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
            </header>
            @RenderBody()
            <footer class="footer">
                <div class="botn-9"><div class="botn-6 valign-text-middle inter-medium-white-16px">botón</div></div>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/js")
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)

</body>



</html>